-- ClassPulse — Seed: 50 Avatars (linh vật)
INSERT INTO avatars (id, name, emoji, color, svg_path, category) VALUES
(1,  'Cáo',          '🦊', '#FF6B35', '/avatars/fox.svg',          'mammal'),
(2,  'Thỏ',          '🐰', '#FFB5C2', '/avatars/rabbit.svg',       'mammal'),
(3,  'Gấu',          '🐻', '#8B4513', '/avatars/bear.svg',         'mammal'),
(4,  'Gấu trúc',     '🐼', '#2D2D2D', '/avatars/panda.svg',        'mammal'),
(5,  'Koala',        '🐨', '#808080', '/avatars/koala.svg',        'mammal'),
(6,  'Sư tử',        '🦁', '#DAA520', '/avatars/lion.svg',         'mammal'),
(7,  'Chim cánh cụt','🐧', '#1C1C1C', '/avatars/penguin.svg',      'bird'),
(8,  'Mèo',          '🐱', '#F4A460', '/avatars/cat.svg',          'mammal'),
(9,  'Chó',          '🐶', '#DEB887', '/avatars/dog.svg',          'mammal'),
(10, 'Hamster',      '🐹', '#FFEAA7', '/avatars/hamster.svg',      'mammal'),
(11, 'Ếch',          '🐸', '#27AE60', '/avatars/frog.svg',         'mammal'),
(12, 'Cú',           '🦉', '#6C3483', '/avatars/owl.svg',          'bird'),
(13, 'Bướm',         '🦋', '#AF7AC5', '/avatars/butterfly.svg',    'insect'),
(14, 'Ong',          '🐝', '#F1C40F', '/avatars/bee.svg',          'insect'),
(15, 'Bọ rùa',       '🐞', '#E74C3C', '/avatars/ladybug.svg',      'insect'),
(16, 'Cá heo',       '🐬', '#3498DB', '/avatars/dolphin.svg',      'sea'),
(17, 'Hồng hạc',     '🦩', '#E91E8C', '/avatars/flamingo.svg',     'bird'),
(18, 'Rùa',          '🐢', '#2E8B57', '/avatars/turtle.svg',       'sea'),
(19, 'Vẹt',          '🦜', '#E74C3C', '/avatars/parrot.svg',       'bird'),
(20, 'Bạch tuộc',    '🐙', '#9B59B6', '/avatars/octopus.svg',      'sea'),
(21, 'Voi',          '🐘', '#95A5A6', '/avatars/elephant.svg',     'mammal'),
(22, 'Hươu',         '🦌', '#A0522D', '/avatars/deer.svg',         'mammal'),
(23, 'Sóc',          '🐿️', '#D2691E', '/avatars/squirrel.svg',     'mammal'),
(24, 'Nhím',         '🦔', '#8B7355', '/avatars/hedgehog.svg',     'mammal'),
(25, 'Cá vàng',      '🐟', '#FF8C00', '/avatars/goldfish.svg',     'sea'),
(26, 'Cua',          '🦀', '#DC143C', '/avatars/crab.svg',         'sea'),
(27, 'Sao biển',     '⭐',  '#FF69B4', '/avatars/starfish.svg',     'sea'),
(28, 'Cá voi',       '🐳', '#4169E1', '/avatars/whale.svg',        'sea'),
(29, 'Chim sẻ',      '🐦', '#CD853F', '/avatars/sparrow.svg',      'bird'),
(30, 'Đại bàng',     '🦅', '#4A4A4A', '/avatars/eagle.svg',        'bird'),
(31, 'Thiên nga',    '🦢', '#F0F0F0', '/avatars/swan.svg',         'bird'),
(32, 'Gà con',       '🐥', '#FFD700', '/avatars/chick.svg',        'bird'),
(33, 'Hổ',           '🐯', '#FF8C00', '/avatars/tiger.svg',        'mammal'),
(34, 'Ngựa',         '🐴', '#8B4513', '/avatars/horse.svg',        'mammal'),
(35, 'Kỳ lân',       '🦄', '#DDA0DD', '/avatars/unicorn.svg',      'mammal'),
(36, 'Khỉ',          '🐵', '#D2691E', '/avatars/monkey.svg',       'mammal'),
(37, 'Gấu bắc cực', '🐻', '#B0E0E6', '/avatars/polar-bear.svg',   'mammal'),
(38, 'Chuột',        '🐭', '#C0C0C0', '/avatars/mouse.svg',        'mammal'),
(39, 'Lợn',          '🐷', '#FFB6C1', '/avatars/pig.svg',          'mammal'),
(40, 'Bò',           '🐮', '#F5F5DC', '/avatars/cow.svg',          'mammal'),
(41, 'Cừu',          '🐑', '#FFFAF0', '/avatars/sheep.svg',        'mammal'),
(42, 'Kangaroo',     '🦘', '#CD853F', '/avatars/kangaroo.svg',     'mammal'),
(43, 'Cá sấu',       '🐊', '#006400', '/avatars/crocodile.svg',    'sea'),
(44, 'Rắn',          '🐍', '#228B22', '/avatars/snake.svg',        'mammal'),
(45, 'Ốc sên',       '🐌', '#DEB887', '/avatars/snail.svg',        'insect'),
(46, 'Kiến',         '🐜', '#2F4F4F', '/avatars/ant.svg',          'insect'),
(47, 'Chuồn chuồn', '🪰',  '#00CED1', '/avatars/dragonfly.svg',   'insect'),
(48, 'Tắc kè',       '🦎', '#32CD32', '/avatars/gecko.svg',        'mammal'),
(49, 'Hải cẩu',      '🦭', '#778899', '/avatars/seal.svg',         'sea'),
(50, 'Tuần lộc',     '🦌', '#8B0000', '/avatars/reindeer.svg',     'mammal');
